config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root 'cars#index'
  post 'cars/search'
  resources :transmissions
  resources :states
  resources :makes
  resources :cars do
    member do
      put 'like' => 'cars#like'
    end
  end
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/make.rb
class Make < ApplicationRecord
  has_and_belongs_to_many :cars
end

app/controllers/makes_controller.rb
class MakesController < ApplicationController
  before_action :set_make, only: [:show, :edit, :update, :destroy]
  before_action :is_admin!
  # GET /makes
  # GET /makes.json
  def index
    @makes = Make.all
  end

  # GET /makes/1
  # GET /makes/1.json
  def show
  end

  # GET /makes/new
  def new
    @make = Make.new
  end

  # GET /makes/1/edit
  def edit
  end

  # POST /makes
  # POST /makes.json
  def create
    @make = Make.new(make_params)

    respond_to do |format|
      if @make.save
        format.html { redirect_to @make, notice: 'Make was successfully created.' }
        format.json { render :show, status: :created, location: @make }
      else
        format.html { render :new }
        format.json { render json: @make.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /makes/1
  # PATCH/PUT /makes/1.json
  def update
    respond_to do |format|
      if @make.update(make_params)
        format.html { redirect_to @make, notice: 'Make was successfully updated.' }
        format.json { render :show, status: :ok, location: @make }
      else
        format.html { render :edit }
        format.json { render json: @make.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /makes/1
  # DELETE /makes/1.json
  def destroy
    @make.destroy
    respond_to do |format|
      format.html { redirect_to makes_url, notice: 'Make was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_make
      @make = Make.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def make_params
      params.require(:make).permit(:name)
    end
end

app/helpers/makes_helper.rb
module MakesHelper
end

app/views/makes/_form.html.erb
<%= form_with(model: make, local: true) do |form| %>
  <% if make.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(make.errors.count, "error") %> prohibited this make from being saved:</h2>

      <ul>
        <% make.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/makes/edit.html.erb
<h1>Editing Make</h1>

<%= render 'form', make: @make %>

<%= link_to 'Show', @make %> |
<%= link_to 'Back', makes_path %>

app/views/makes/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Makes</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @makes.each do |make| %>
      <tr>
        <td><%= make.name %></td>
        <td><%= link_to 'Show', make %></td>
        <td><%= link_to 'Edit', edit_make_path(make) %></td>
        <td><%= link_to 'Destroy', make, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Make', new_make_path %>

app/views/makes/new.html.erb
<h1>New Make</h1>

<%= render 'form', make: @make %>

<%= link_to 'Back', makes_path %>

app/views/makes/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @make.name %>
</p>

<%= link_to 'Edit', edit_make_path(@make) %> |
<%= link_to 'Back', makes_path %>