config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root 'cars#index'
  post 'cars/search'
  resources :transmissions
  resources :states
  resources :makes
  resources :cars do
    member do
      put 'like' => 'cars#like'
    end
  end
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/transmission.rb
class Transmission < ApplicationRecord
  has_and_belongs_to_many :cars
end

app/controllers/transmissions_controller.rb
class TransmissionsController < ApplicationController
  before_action :set_transmission, only: [:show, :edit, :update, :destroy]
  before_action :is_admin!
  # GET /transmissions
  # GET /transmissions.json
  def index
    @transmissions = Transmission.all
  end

  # GET /transmissions/1
  # GET /transmissions/1.json
  def show
  end

  # GET /transmissions/new
  def new
    @transmission = Transmission.new
  end

  # GET /transmissions/1/edit
  def edit
  end

  # POST /transmissions
  # POST /transmissions.json
  def create
    @transmission = Transmission.new(transmission_params)

    respond_to do |format|
      if @transmission.save
        format.html { redirect_to @transmission, notice: 'Transmission was successfully created.' }
        format.json { render :show, status: :created, location: @transmission }
      else
        format.html { render :new }
        format.json { render json: @transmission.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /transmissions/1
  # PATCH/PUT /transmissions/1.json
  def update
    respond_to do |format|
      if @transmission.update(transmission_params)
        format.html { redirect_to @transmission, notice: 'Transmission was successfully updated.' }
        format.json { render :show, status: :ok, location: @transmission }
      else
        format.html { render :edit }
        format.json { render json: @transmission.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /transmissions/1
  # DELETE /transmissions/1.json
  def destroy
    @transmission.destroy
    respond_to do |format|
      format.html { redirect_to transmissions_url, notice: 'Transmission was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_transmission
      @transmission = Transmission.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def transmission_params
      params.require(:transmission).permit(:transmission)
    end
end

app/helpers/transmissions_helper.rb
module TransmissionsHelper
end

app/views/transmissions/_form.html.erb
<%= form_with(model: transmission, local: true) do |form| %>
  <% if transmission.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(transmission.errors.count, "error") %> prohibited this transmission from being saved:</h2>

      <ul>
        <% transmission.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :transmission %>
    <%= form.text_field :transmission %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/transmissions/edit.html.erb
<h1>Editing Transmission</h1>

<%= render 'form', transmission: @transmission %>

<%= link_to 'Show', @transmission %> |
<%= link_to 'Back', transmissions_path %>

app/views/transmissions/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Transmissions</h1>

<table>
  <thead>
    <tr>
      <th>Transmission</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @transmissions.each do |transmission| %>
      <tr>
        <td><%= transmission.transmission %></td>
        <td><%= link_to 'Show', transmission %></td>
        <td><%= link_to 'Edit', edit_transmission_path(transmission) %></td>
        <td><%= link_to 'Destroy', transmission, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Transmission', new_transmission_path %>

app/views/transmissions/new.html.erb
<h1>New Transmission</h1>

<%= render 'form', transmission: @transmission %>

<%= link_to 'Back', transmissions_path %>

app/views/transmissions/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Transmission:</strong>
  <%= @transmission.transmission %>
</p>

<%= link_to 'Edit', edit_transmission_path(@transmission) %> |
<%= link_to 'Back', transmissions_path %>