config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root 'cars#index'
  post 'cars/search'
  resources :transmissions
  resources :states
  resources :makes
  resources :cars do
    member do
      put 'like' => 'cars#like'
    end
  end
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/car.rb
class Car < ApplicationRecord
  has_and_belongs_to_many :makes
  has_and_belongs_to_many :states
  has_and_belongs_to_many :transmissions
  belongs_to :user
  has_one_attached :thumbnail
  has_many_attached :images
  has_rich_text :description
  validates :title, presence: true
  validates :description, presence: false
  validate :image_type
  acts_as_votable

  def resized_thumbnail
    thumbnail.variant(resize: "240x135!")
  end

  def manyimage input
    return self.images[input].variant(resize: '350x250!').processed
  end
  
  private
  def image_type
    if images.attached? == false
      errors.add(:images, "are missing!")
    end
    images.each do |image|
      if !image.content_type.in?(%('image/jpeg image/jpg image/png'))
        errors.add(:images, 'needs to be a JPEG, JPG or PNG')
      end
    end
  end
end

app/controllers/cars_controller.rb
# frozen_string_literal: true

class CarsController < ApplicationController
  before_action :set_car, only: %i[show edit update destroy like]
  before_action :set_makes, except: %i[show destroy]
  before_action :is_admin!, except: [:index, :show, :edit, :update, :like]
  before_action :authenticate_user!, except: [:show, :index]


  def index
    set_cars_and_make_with_criteria(params[:make], params[:order], '')
  end

  def search
    set_cars_and_make_with_criteria(params[:make], params[:order] , params[:state])
  end


  def show; end

  def new
    @car = Car.new
  end

  def edit; end

  def create
    @car = Car.new(car_params)
    @car.user = current_user

    respond_to do |format|
      if @car.save
        format.html { redirect_to @car, notice: 'Car was successfully created.' }
        format.json { render :show, status: :created, location: @car }
      else
        format.html { render :new }
        format.json { render json: @car.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      if @car.update(car_params)
        format.html { redirect_to cars_path, notice: 'Car was successfully updated.' }
        format.json { render :show, status: :ok, location: @car }
      else
        format.html { render :edit }
        format.json { render json: @car.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @car.destroy
    respond_to do |format|
      format.html { redirect_to cars_url, notice: 'Car was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def like
    if current_user.voted_for? @car
      @car.unlike_by current_user
    else
      @car.liked_by current_user
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_car
    @car = Car.find(params[:id])
  end

  def set_makes
    @makes = Make.all
  end

  def set_states
    @states = State.all
  end

  # Only allow a list of trusted parameters through.
  def car_params
    params.require(:car).permit(:title, :description, :feature, :price, :model, :thumbnail, :year, :color, :miles, images: [], make_ids: [], state_ids: [])
  end

  def set_cars_and_make_with_criteria(requested_make, requested_order, requested_state)
    if requested_make.nil? || requested_make.eql?('All')
      cars_by_make = Car.all
      @make_name = 'All'
    else
      cars_by_make = filter_cars_by_make(requested_make)
      @make_name = requested_make
    end

    if requested_state == '' || requested_state.nil? || requested_state.eql?('All')
      cars_by_state = cars_by_make
    else
      cars_by_state = filter_cars_by_state(requested_state, cars_by_make)
    end
    @order = requested_order
    order_cars(requested_order, cars_by_state)
  end

  def filter_cars_by_make(make_name)
    @make = Make.find_by(name: make_name)
    cars = if @make.nil?
             Car.none
           else
             @make.cars
           end
  end

  def filter_cars_by_state(state_name, cars_by_make)
    @make = State.find_by(state: state_name)
    cars = if @make.nil?
             # Car.none
           else
             @make.cars.where(id: cars_by_make.pluck(:id))

           end

  end

  def order_cars(_order, _cars)
    @cars = case _order
              when 'A-Z'
                _cars.order('title ASC')
              when 'Z-A'
                _cars.order('title DESC')
              when 'Highest Priced First'
                _cars.order('price DESC')
              when 'Lowest Priced First'
                _cars.order('price ASC')
              when 'Newest First'
                _cars.order('created_at DESC')
              when 'Oldest First'
                _cars.order('created_at ASC')
              else
                _cars.order('title ASC')
            end
  end
end

app/helpers/cars_helper.rb
module CarsHelper
end

app/views/cars/_feature.html.erb
<div class="container">
    <h1 style="text-align:center">
      <%= link_to "Featured Cars", root_path %>
    </h1>
</div>
<% @cars.each do |car| %>
  <div class="container">
    <div class="row">
      <%= form_with(model: car, local: true) do |form| %>
      <div class="col">
        <div class="form-group row">
          <div class="col">
            <%= form.text_field :title, class:'form-control' %>
          </div>
          <div class="col-form-label">
            <%= form.label "Feature", class: 'col-form-label' %>
          </div>
          <div class="col"
            <%= form.check_box :feature, class:'form-control' %>
          </div>
          <div class="col">
            <%= form.submit "Update" %>
          </div>
        </div>
      </div>
      <% end %>
      <div class="col">
        <%= link_to "Delete", car, method: :delete, data: {confirm: "Are you sure you want to delete the listing?"}, class:'btn btn-danger' %>
      </div>
    </div>
  </div>
<% end %>

app/views/cars/_form.html.erb
<div class="container">
  <%= simple_form_for(@car) do |f| %>
    <% if car.errors.any? %>
      <div id="error_explanation">
        <h2><%= pluralize(car.errors.count, "error") %> prohibited this car from being saved:</h2>

        <ul>
          <% car.errors.full_messages.each do |message| %>
            <li><%= message %></li>
          <% end %>
        </ul>
      </div>
    <% end %>

    <div class="field">
      <%= f.input :title, :input_html => {:style=> 'width: 700px'} %>
    </div>

    <div class="field">
      <div class="form-group car_make_ids">
        <label class="" for="car_description">Description</label><br>
        <%= f.cktext_area :description %>
      </div>
    </div>

    <div class="field">
      <div class="form-group car_make_ids">
        <label class="" for="car_make_ids">Select Makes</label><br>
        <%= f.collection_select :make_ids, Make.all, :id, :name, {}, {multiple:true, class: "select2", :style=> 'width: 700px'} %>
      </div>
    </div>

    <div class="field">
      <%= f.input :model, :input_html => {:style=> 'width: 700px'} %>
    </div>

    <div class="field">
      <%= f.input :price, :input_html => {:style=> 'width: 700px'} %>
    </div>

    <div class="field">
      <%= f.input :year, :input_html => {:style=> 'width: 700px'} %>
    </div>

    <div class="field">
      <%= f.input :color, :input_html => {:style=> 'width: 700px'} %>
    </div>

    <div class="field">
      <%= f.input :miles, :input_html => {:style=> 'width: 700px'} %>
    </div>

    <div class="field">
      <div class="form-group car_state_ids">
        <label class="" for="car_state_ids">Select State</label><br>
        <%= f.collection_select :state_ids, State.all, :id, :state, {}, {multiple:true, class: "select2", :style=> 'width: 700px'} %>
      </div>
    </div>

    <div class="field">
      <%= f.file_field :thumbnail %>
    </div>

    <div class="field">
      <%= f.file_field :images, multiple: true %>
    </div>

    <div class="field">
      <%= "Feature Car?" %>
      <%= f.check_box :feature %>
      <%= "($25)" %>
    </div>

    <div class="actions">
      <%= f.submit %>
    </div>
  <% end %>
</div>

app/views/cars/_like_link.html.erb
<% if current_user %>
<% vote_text = current_user&.voted_for?(car) ? "No longer interested" : "Yes, I'm interested!" %>

<%= link_to vote_text, like_car_path(car), method: :put, remote: :true, class: 'like-post' %>
<% else %>
<%= link_to "Yes, I'm interested!", new_user_session_path, class: 'like-post' %>
<% end %>

app/views/cars/_likes.html.erb
<%= car.get_upvotes.size %>
<%= "interested" %>

app/views/cars/_makes.html.erb
<div class="container">
    <h1><%= link_to @make_name, root_path %></h1>
    <div id="cars">
        <% @cars.each do |car| %>
        <% if car.thumbnail.attached? %>
        <div class="item">
            <%= link_to image_tag(car.resized_thumbnail), car_path(car, make: @make_name, order: @order) %>
            <span class="caption">
            <%= link_to car.title, car %><p>
            Color: <%= link_to car.color, car %> 
            Price: $<%= link_to car.price, car %><br>
            Year: <%= link_to car.year, car %>
            State: <% car.states.each do |state| %>
                    <%= link_to state.state, root_path(state: state.state) %>
                  <% end %>
            <% else %>
            <div style="width: 240px; height: 135px">
                <%= link_to car.title, car %>
            </div>
            <% end %>
        </div>
        <% end %>
    </div>
</div>

app/views/cars/edit.html.erb
<h1>Editing Car</h1>

<%= render 'form', car: @car %>

<%= link_to 'Show', @car %> |
<%= link_to 'Back', cars_path %>

app/views/cars/index.html.erb
<div class="search-container">
  <%= form_tag(cars_search_path, remote: true) do %>
      <div class="field">
        <%= label_tag :make, "Make: " %>

        <%= select_tag :make, options_from_collection_for_select(
            @makes.to_a.unshift(Make.new(id: 0, name: "All")),
            "name",
            "name",
            "0") %>
        <%= label_tag :state, "State: " %>
        <%= select_tag :state, options_for_select(["All"] + State.all.map{|c| [c.state]}) %>

        <%= label_tag :order, "Order" %>
        <%= select_tag :order, options_for_select([
                                                      "A-Z",
                                                      "Z-A",
                                                      "Highest Priced First",
                                                      "Lowest Priced First",
                                                      "Newest First",
                                                      "Oldest First"
                                                  ]), {include_blank: "Order"} %>


        <%= submit_tag "Search" %>
      </div>
  <% end %>
</div>


<div id="makes">
  <%= render 'cars/makes' %>
</div>
<%= render 'layouts/footer' %>

app/views/cars/like.js.erb
$("#like-count").html("<%= j render 'cars/likes', car: @car %>");
$("#like-link").html("<%= j render 'cars/like_link', car: @car %>");

app/views/cars/new.html.erb
<h1>New Car</h1>

<%= render 'form', car: @car %>

<%= link_to 'Back', cars_path %>

app/views/cars/search.js.erb
var makes = document.getElementById("makes");
var cars = document.getElementById("cars")
window.history.replaceState(null, null, "?make=<%= @make_name %>?order=<%= @order%>");
makes.innerHTML = "<%= j render 'cars/makes' %>";

app/views/cars/show.html.erb
<div class="container">
    <div class="row">
        <div class="col-4">
            <%= image_tag(@car.thumbnail, class:'img-fluid') if @car.thumbnail.attached? %>
            <div class="row">
                <div class="col-12">
                    <h4>
                        Are You Interested?
                    </h4>
                </div>
                <div class="col-12">
                    <h5>
                        <div id="like-count">
                            <%= render 'cars/likes', car: @car %>
                        </div>
                        <div id="like-link">
                            <%= render 'cars/like_link', car: @car %>
                        </div>
                        <hr />
                    </h5>
                </div>
            </div>
            <div class="row">
                <div class="col-12">
                    <h6>
                       <button type="button" class="btn btn-outline-primary">Message Owner</button>
                    </h6>
                </div>
                <div class="col-6">
                </div>
                <div class="col-12">
                  <% if current_user&.admin %>
                  <div class="btn-group">
                      <%= link_to 'Edit', edit_car_path(@car), class: 'btn btn-warning' %>
                      <%= link_to 'Delete', @car, method: :delete, class: 'btn btn-danger' %>
                  </div>
                  <% end %>
                  <p>
                  <h4>Car's Location</h4>
                  <strong>State:</strong>
                  <% @car.states.each do |state| %>
                    <%= link_to state.state, root_path(state: state.state) %>
                  <% end %>
                </div>
            </div>
        </div>
        <div class="col-8">
            <h1>
                <% if params[:make].nil? %>
                <%= link_to @car.title, root_path %>
                <% else %>
                <%= link_to @car.title, root_path(make: params[:make], order: params[:order]) %>
                <% end %>
            </h1>
            <div class="container">
                <%= @car.description %>
                <p>
                <div class="table-responsive-sm">
                  <table class="table">
                    <thead>
                      <tr>
                        <th scope="col">Make</th>
                        <th scope="col">Model</th>
                        <th scope="col">Year</th>
                        <th scope="col">Color</th>
                        <th scope="col">Miles</th>
                        <th scope="col">Price</th>
                      </tr>
                    </thead>
                    <tbody>
                      <tr>
                        <th scope="row"><% @car.makes.each do |make| %>
                        <%= link_to make.name, cars_path(make: make.name) %>
                        <% end %></th>
                        <td><%= @car.model %></td>
                        <td><%= @car.year %></td>
                        <td><%= @car.color %></td>
                        <td><%= @car.miles %></td>
                        <td><%= @car.price %></td>
                      </tr>
                    </body>
                  </table>
                </div>
            </div>
        </div>
    </div>
</div>
<p>
<div class="container">
  <h3>Photos</h3>
  <% (0...@car.images.count).each do |image| %>
                    <%= image_tag(@car.manyimage(image)) %>
                    <% end %>
</div>

<%= link_to 'Edit', edit_car_path(@car) %> |
<%= link_to 'Back', cars_path %>